teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left stick vertical
    axis_angular:
      yaw: 2  # Right stick horizontal
    scale_linear:
      x: 0.5
    scale_angular:
      yaw: 1.0
    require_enable_button: false